global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'fintech-platform'

# Scrape configurations
scrape_configs:
  # Scrape Workers metrics
  - job_name: 'workers'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.20.62.22:5002'] # Workers expose metrics on port 5002
        labels:
          service: 'fraud-detection-worker'

  # Future: Add API metrics
  # - job_name: 'api'
  #   scrape_interval: 15s
  #   static_configs:
  #     - targets: ['host.docker.internal:5153']
  #       labels:
  #         service: 'fintech-api'
